"""
--- Description ---

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        
        alpha = "abcdefghijklmnopqrstuvwxyz"
        for letter in alpha:
            if t.count(letter) > s.count(letter):
                return letter

"""
--- Submission ---

Runtime: 41 ms, faster than 84.17% of Python3 online submissions for Find the Difference.
Memory Usage: 13.9 MB, less than 31.96% of Python3 online submissions for Find the Difference.
"""